#!/bin/bash

# stop here if shell is non-interactive
[[ $- == *i* ]] || return 0

source "$HOME/.dotfiles/shell/utils.bashrc"

source-if-ok $HOME/.dotfiles/shell/bashrc.d/*

source-if-ok $HOME/.dotfiles/shell/bash-completion.d/*


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
