#!/bin/bash

if [ -z $SHELL_CONFIGS_VERSION ] ; then
  export SHELL_CONFIGS_VERSION="-1"
fi

if [ ! -f "$HOME/.shell-configs-latest-version" ] ; then
  echo 0 >"$HOME/.shell-configs-latest-version"
fi

shel_configs_latest_version=`cat "$HOME/.shell-configs-latest-version"`

if [ $SHELL_CONFIGS_VERSION -eq $shel_configs_latest_version ] ; then
  # script up to date
  unset shel_configs_latest_version
  return 0
fi

#-------------------------------------------------------------------------------

source "$HOME/.shell/script-utils"

source-if-ok $HOME/.shell/env

source-if-ok $HOME/.shell/rc.d/*

source-if-ok $HOME/.shell/bash-completion.d/*

### Settings ###

# needed here for fzf before source ~/.fzf.bash
set -o vi
# must be before bash_competion
# (or warning on auto completion for cmd starting with g++:
# bash: warning: programmable_completion: g++: possible retry loop)
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# git completion
if [[ $HOSTNAME != *grid.pub.ro ]] ; then
  [ -f ~/.git-completion.bash ] && source ~/.git-completion.bash
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

#-------------------------------------------------------------------------------

export SHELL_CONFIGS_VERSION=$shel_configs_latest_version
unset shel_configs_latest_version

