#!/bin/bash

source "$HOME/.shell/script-utils"

source-if-ok $HOME/.shell/env

# stop here if shell is non-interactive
[[ $- == *i* ]] || return 0

source-if-ok $HOME/.shell/rc.d/*

source-if-ok $HOME/.shell/bash-completion.d/*

### Settings ###

# needed here for fzf before source ~/.fzf.bash
set -o vi
# must be before bash_competion
# (or warning on auto completion for cmd starting with g++:
# bash: warning: programmable_completion: g++: possible retry loop)
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# git completion
if [[ $HOSTNAME != *grid.pub.ro ]] ; then
  [ -f ~/.git-completion.bash ] && source ~/.git-completion.bash
fi

