#!/bin/bash

# needed here for fzf before source ~/.fzf.bash
# this enables vi mode in bash only
set -o vi

export FZF_DEFAULT_COMMAND="find -L \$PWD -mindepth 1 -type d \
    \\( -fstype 'sysfs' \
       -o -fstype 'devfs' \
       -o -fstype 'devtmpfs' \
       -o -fstype 'proc' \
       -o -name '.git' \
       -o -name '.cache' \
       -o -name '__py_cache__' \
       -o -name '.vscode*' \
       -o -path '*.vim/bundle' \
       -o -path '*.vim/undo' \
       -o -path '/home/mihail.balan/snap' \
       \\) -prune \
    -o -printf '%P\\n' 2> /dev/null "

export FZF_CTRL_T_COMMAND="find -L \$PWD -mindepth 1 -type d \
    \\( -fstype 'sysfs' \
       -o -fstype 'devfs' \
       -o -fstype 'devtmpfs' \
       -o -fstype 'proc' \
       -o -name '.git' \
       -o -name '.cache' \
       -o -name '__py_cache__' \
       -o -name '.vscode*' \
       -o -path '*.vim/bundle' \
       -o -path '*.vim/undo' \
       -o -path '/home/mihail.balan/snap' \
    \\) -prune \
    -o \( -type f -o -type d \) \
    -printf '%P\\n' 2> /dev/null "

export FZF_ALT_C_COMMAND="command find -L \$PWD -mindepth 1 -type d \
    \\( -fstype 'sysfs' \
        -o -fstype 'devfs' \
        -o -fstype 'devtmpfs' \
        -o -fstype 'proc' \
       -o -name '.git' \
       -o -name '.cache' \
       -o -name '__py_cache__' \
       -o -name '.vscode*' \
       -o -path '*.vim/bundle' \
       -o -path '*.vim/undo' \
       -o -path '/home/mihail.balan/snap' \
       \\) -prune \
    -o -type d \
    -printf '%P\\n' 2> /dev/null "

[ -f ~/.fzf.bash ] && source ~/.fzf.bash


if command -v powerline-daemon >/dev/null 2>&1 ; then
    powerline-daemon -q
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASH_SELECT=1
    . ~/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
fi
