#!/bin/bash

# function to mkdir and cd into it
mkcd() {
    mkdir -- "$1" && cd -- "$1"
}

# print filename and linenumber of a function definition
whereis-func() {
    shopt -s extdebug;
    declare -F $1;
    shopt -u extdebug
}


# function to toggle the bash promp between cwd and basename of cwd
# it basically toggles the case of \w in $PS1
toggle-cwd-prompt() {
    local NEW_PS1
    # to upper
    NEW_PS1=$(echo "$PS1" | sed 's/\\w\\\$/\\W\\\$/')
    # if not substituted
    if [ "$PS1" = "$NEW_PS1" ]
    then
        # to lower
        NEW_PS1=$(echo "$PS1" | sed 's/\\W\\\$/\\w\\\$/')
    fi
    PS1=$NEW_PS1
}

#
shell-configs-update() {
    if [ ! -f "$HOME/.shell-configs-latest-version" ] ; then
        return 0
    fi

    local shel_configs_latest_version=`cat "$HOME/.shell-configs-latest-version"`
    let "shel_configs_latest_version+=1"
    echo $shel_configs_latest_version >"$HOME/.shell-configs-latest-version"

    source "$HOME/.shell/pk"
}

